services:
  - type: web
    name: aqarak-app
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: MAPBOX_TOKEN
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: ADMIN_EMAIL
        sync: false
      - key: ADMIN_PHONE
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: DISCORD_WEBHOOK_URL
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: PAYMOB_API_KEY
        sync: false
      - key: PAYMOB_HMAC
        sync: false
      - key: PAYMOB_IFRAME_ID
        sync: false
      - key: PAYMOB_INTEGRATION_CARD
        sync: false
      - key: PAYMOB_INTEGRATION_WALLET
        sync: false
